
// this file is generated — do not edit it


declare module "svelte/elements" {
	export interface HTMLAttributes<T> {
		'data-sveltekit-keepfocus'?: true | '' | 'off' | undefined | null;
		'data-sveltekit-noscroll'?: true | '' | 'off' | undefined | null;
		'data-sveltekit-preload-code'?:
			| true
			| ''
			| 'eager'
			| 'viewport'
			| 'hover'
			| 'tap'
			| 'off'
			| undefined
			| null;
		'data-sveltekit-preload-data'?: true | '' | 'hover' | 'tap' | 'off' | undefined | null;
		'data-sveltekit-reload'?: true | '' | 'off' | undefined | null;
		'data-sveltekit-replacestate'?: true | '' | 'off' | undefined | null;
	}
}

export {};


declare module "$app/types" {
	type MatcherParam<M> = M extends (param : string) => param is (infer U extends string) ? U : string;

	export interface AppTypes {
		RouteId(): "/(app)" | "/" | "/(app)/admin" | "/(app)/admin/aniversariantes" | "/(app)/admin/avisos" | "/(app)/admin/crm" | "/(app)/admin/email" | "/(app)/admin/empresas" | "/(app)/admin/empresas/[id]" | "/(app)/admin/financeiro" | "/(app)/admin/modulos-sistema" | "/(app)/admin/parametros-importacao" | "/(app)/admin/permissoes" | "/(app)/admin/permissoes/[id]" | "/(app)/admin/planos" | "/(app)/admin/tipos-usuario" | "/(app)/admin/tipos-usuario/[id]" | "/(app)/admin/usuarios" | "/(app)/admin/usuarios/[id]" | "/(app)/aniversariantes" | "/api" | "/api/auth" | "/api/auth/set-session" | "/api/v1 2" | "/api/v1" | "/api/v1/admin" | "/api/v1/admin/auth" | "/api/v1/admin/auth/mfa-status" | "/api/v1/admin/auth/reset-mfa" | "/api/v1/admin/auth/set-password" | "/api/v1/admin/avisos" | "/api/v1/admin/avisos/send" | "/api/v1/admin/crm" | "/api/v1/admin/email" | "/api/v1/admin/email/test" | "/api/v1/admin/empresas" | "/api/v1/admin/empresas/[id]" | "/api/v1/admin/logs" | "/api/v1/admin/maintenance" | "/api/v1/admin/master-empresas" | "/api/v1/admin/modulos-sistema" | "/api/v1/admin/permissoes" | "/api/v1/admin/permissoes/[id]" | "/api/v1/admin/planos" | "/api/v1/admin/summary" | "/api/v1/admin/system-modules" | "/api/v1/admin/tipos-usuario" | "/api/v1/admin/tipos-usuario/[id]" | "/api/v1/admin/tipos-usuario/[id]/permissoes" | "/api/v1/admin/usuarios" | "/api/v1/admin/usuarios/[id]" | "/api/v1/agenda" | "/api/v1/agenda/create" | "/api/v1/agenda/delete" | "/api/v1/agenda/range" | "/api/v1/agenda/update" | "/api/v1/cards" | "/api/v1/cards/aniversario.svg" | "/api/v1/cards/render.png" | "/api/v1/cards/render.svg" | "/api/v1/cards/render" | "/api/v1/cidades" | "/api/v1/cidades/[id]" | "/api/v1/circuitos" | "/api/v1/circuitos/[id]" | "/api/v1/client-error" | "/api/v1/clientes" | "/api/v1/clientes/avisos" | "/api/v1/clientes/avisos/history" | "/api/v1/clientes/avisos/send" | "/api/v1/clientes/avisos/templates" | "/api/v1/clientes/create" | "/api/v1/clientes/delete" | "/api/v1/clientes/historico" | "/api/v1/clientes/list" | "/api/v1/clientes/resolve-import" | "/api/v1/clientes/template-dispatches" | "/api/v1/clientes/templates" | "/api/v1/clientes/templates/send" | "/api/v1/clientes/[id]" | "/api/v1/clientes/[id]/acompanhantes" | "/api/v1/clientes/[id]/acompanhantes/[acompanhanteId]" | "/api/v1/conciliacao" | "/api/v1/conciliacao/assign" | "/api/v1/conciliacao/changes" | "/api/v1/conciliacao/delete" | "/api/v1/conciliacao/executions" | "/api/v1/conciliacao/existing" | "/api/v1/conciliacao/import" | "/api/v1/conciliacao/list" | "/api/v1/conciliacao/lookup" | "/api/v1/conciliacao/options" | "/api/v1/conciliacao/rateio-info" | "/api/v1/conciliacao/revert" | "/api/v1/conciliacao/run" | "/api/v1/conciliacao/summary" | "/api/v1/conciliacao/update-valores" | "/api/v1/consultorias" | "/api/v1/consultorias/ics" | "/api/v1/convites" | "/api/v1/convites/accept" | "/api/v1/convites/send" | "/api/v1/crm" | "/api/v1/crm/library" | "/api/v1/crm/signature" | "/api/v1/cron" | "/api/v1/cron/alerta-comissao" | "/api/v1/cron/lembretes-consultoria" | "/api/v1/dashboard" | "/api/v1/dashboard/aniversariantes" | "/api/v1/dashboard/consultorias" | "/api/v1/dashboard/debug-aggregates" | "/api/v1/dashboard/follow-ups" | "/api/v1/dashboard/summary" | "/api/v1/dashboard/viagens" | "/api/v1/dashboard/widgets" | "/api/v1/debug-comissao" | "/api/v1/debug" | "/api/v1/debug/escala-diag" | "/api/v1/debug/permissions" | "/api/v1/debug/vendas-recibos-diff" | "/api/v1/debug/viagens-diag" | "/api/v1/documentacao" | "/api/v1/documentos-viagens" | "/api/v1/documentos-viagens/create" | "/api/v1/documentos-viagens/delete" | "/api/v1/documentos-viagens/list" | "/api/v1/documentos-viagens/save-template" | "/api/v1/documentos-viagens/update" | "/api/v1/equipe" | "/api/v1/equipe/relacao" | "/api/v1/financeiro" | "/api/v1/financeiro/ajustes-vendas" | "/api/v1/financeiro/ajustes-vendas/list" | "/api/v1/financeiro/ajustes-vendas/save" | "/api/v1/financeiro/caixa" | "/api/v1/financeiro/comissoes" | "/api/v1/financeiro/comissoes/calcular" | "/api/v1/financeiro/comissoes/pagamento" | "/api/v1/financeiro/comissoes/regras" | "/api/v1/financeiro/comissoes/regras/[id]" | "/api/v1/financeiro/comissoes/vendedores" | "/api/v1/financeiro/formas-pagamento" | "/api/v1/fornecedores" | "/api/v1/fornecedores/create" | "/api/v1/fornecedores/[id]" | "/api/v1/health" | "/api/v1/importar-vendas" | "/api/v1/menu" | "/api/v1/menu/prefs" | "/api/v1/mural" | "/api/v1/mural/bootstrap" | "/api/v1/mural/company" | "/api/v1/mural/read" | "/api/v1/mural/recados" | "/api/v1/operacao" | "/api/v1/operacao/campanhas" | "/api/v1/operacao/documentos-viagens" | "/api/v1/operacao/preferencias" | "/api/v1/operacao/recados" | "/api/v1/operacao/sac" | "/api/v1/orcamentos" | "/api/v1/orcamentos/cidades-busca" | "/api/v1/orcamentos/cliente-create" | "/api/v1/orcamentos/clientes" | "/api/v1/orcamentos/create" | "/api/v1/orcamentos/delete" | "/api/v1/orcamentos/importar" | "/api/v1/orcamentos/interacao" | "/api/v1/orcamentos/interaction" | "/api/v1/orcamentos/list" | "/api/v1/orcamentos/produtos" | "/api/v1/orcamentos/save" | "/api/v1/orcamentos/status" | "/api/v1/orcamentos/tipos" | "/api/v1/orcamentos/[id]" | "/api/v1/orcamentos/[id]/resumo-venda" | "/api/v1/pagamentos" | "/api/v1/pagamentos/upload" | "/api/v1/pagamentos/[id]" | "/api/v1/pagamentos/[id]/conciliar" | "/api/v1/paises" | "/api/v1/parametros" | "/api/v1/parametros/cambios" | "/api/v1/parametros/commission-rules" | "/api/v1/parametros/empresa" | "/api/v1/parametros/equipe" | "/api/v1/parametros/escalas" | "/api/v1/parametros/metas" | "/api/v1/parametros/nao-comissionaveis" | "/api/v1/parametros/orcamentos-pdf" | "/api/v1/parametros/sistema" | "/api/v1/parametros/tipo-pacotes" | "/api/v1/preferencias" | "/api/v1/preferencias/base" | "/api/v1/preferencias/cidades-busca" | "/api/v1/preferencias/delete" | "/api/v1/preferencias/list" | "/api/v1/preferencias/save" | "/api/v1/preferencias/share-accept" | "/api/v1/preferencias/share-revoke" | "/api/v1/preferencias/share" | "/api/v1/produtos" | "/api/v1/produtos/base" | "/api/v1/produtos/create" | "/api/v1/produtos/tarifas" | "/api/v1/produtos/[id]" | "/api/v1/profile" | "/api/v1/profile/signature" | "/api/v1/push" | "/api/v1/push/subscribe" | "/api/v1/push/unsubscribe" | "/api/v1/relatorios" | "/api/v1/relatorios/base" | "/api/v1/relatorios/cidades-busca" | "/api/v1/relatorios/clientes" | "/api/v1/relatorios/destinos" | "/api/v1/relatorios/produtos-recibos" | "/api/v1/relatorios/produtos" | "/api/v1/relatorios/ranking-vendas" | "/api/v1/relatorios/ranking" | "/api/v1/relatorios/vendas-por-cliente" | "/api/v1/relatorios/vendas-por-destino" | "/api/v1/relatorios/vendas-por-produto" | "/api/v1/relatorios/vendas" | "/api/v1/roteiros" | "/api/v1/roteiros/delete" | "/api/v1/roteiros/dias-busca" | "/api/v1/roteiros/gerar-orcamento" | "/api/v1/roteiros/list" | "/api/v1/roteiros/save" | "/api/v1/roteiros/sugestoes-busca" | "/api/v1/roteiros/sugestoes-remover" | "/api/v1/roteiros/sugestoes-salvar" | "/api/v1/roteiros/[id]" | "/api/v1/subdivisoes" | "/api/v1/tarefas" | "/api/v1/tarefas/clientes" | "/api/v1/tarefas/usuarios" | "/api/v1/tipo-produtos" | "/api/v1/todo" | "/api/v1/todo/batch" | "/api/v1/todo/board" | "/api/v1/todo/category" | "/api/v1/todo/item" | "/api/v1/todo/item/[id]" | "/api/v1/users" | "/api/v1/users/aniversariantes" | "/api/v1/user" | "/api/v1/user/context" | "/api/v1/user/profile" | "/api/v1/vendas" | "/api/v1/vendas/cadastro-base" | "/api/v1/vendas/cadastro-save" | "/api/v1/vendas/cancel" | "/api/v1/vendas/cidades-busca" | "/api/v1/vendas/complementares" | "/api/v1/vendas/create" | "/api/v1/vendas/gestor-equipe" | "/api/v1/vendas/importar-contrato" | "/api/v1/vendas/kpis" | "/api/v1/vendas/list" | "/api/v1/vendas/merge-candidates" | "/api/v1/vendas/merge" | "/api/v1/vendas/recibo-complementar-link" | "/api/v1/vendas/recibo-complementar-remove" | "/api/v1/vendas/recibo-delete" | "/api/v1/vendas/recibo-edit" | "/api/v1/vendas/recibo-notas" | "/api/v1/vendas/recibo-principal" | "/api/v1/vendas/status" | "/api/v1/vendas/[id]" | "/api/v1/viagens" | "/api/v1/viagens/cidades-busca" | "/api/v1/viagens/clientes" | "/api/v1/viagens/cliente" | "/api/v1/viagens/cliente/[id]" | "/api/v1/viagens/create" | "/api/v1/viagens/delete" | "/api/v1/viagens/dossie-batch" | "/api/v1/viagens/dossie" | "/api/v1/viagens/list" | "/api/v1/viagens/[id]" | "/api/v1/voucher-assets" | "/api/v1/vouchers" | "/api/v1/vouchers/create" | "/api/v1/vouchers/delete" | "/api/v1/vouchers/[id]" | "/api/v1/welcome-email" | "/auth" | "/auth/convite" | "/auth/login" | "/auth/logout" | "/auth/mfa" | "/auth/nova-senha" | "/auth/recuperar-senha" | "/auth/register" | "/(app)/cadastros" | "/(app)/cadastros/cidades" | "/(app)/cadastros/circuitos" | "/(app)/cadastros/circuitos/novo" | "/(app)/cadastros/circuitos/[id]" | "/(app)/cadastros/circuitos/[id]/editar" | "/(app)/cadastros/destinos" | "/(app)/cadastros/destinos/novo" | "/(app)/cadastros/destinos/[id]" | "/(app)/cadastros/destinos/[id]/editar" | "/(app)/cadastros/estados" | "/(app)/cadastros/fornecedores" | "/(app)/cadastros/fornecedores/novo" | "/(app)/cadastros/fornecedores/[id]" | "/(app)/cadastros/fornecedores/[id]/editar" | "/(app)/cadastros/lote" | "/(app)/cadastros/paises" | "/(app)/cadastros/produtos" | "/(app)/cadastros/produtos/novo" | "/(app)/cadastros/produtos/[id]" | "/(app)/cadastros/produtos/[id]/editar" | "/calculadora" | "/(app)/clientes" | "/(app)/clientes/novo" | "/(app)/clientes/[id]" | "/(app)/clientes/[id]/editar" | "/(app)/comissoes" | "/(app)/comissoes/fechamento" | "/(app)/consultoria-online" | "/(app)/dashboard" | "/(app)/dashboard/admin" | "/(app)/dashboard/financeiro" | "/(app)/dashboard/geral" | "/(app)/dashboard/gestor" | "/(app)/dashboard/master" | "/(app)/dashboard/vendedor" | "/(app)/debug" | "/(app)/diagnostico" | "/(app)/documentacao" | "/(app)/financeiro" | "/(app)/financeiro/ajustes-vendas" | "/(app)/financeiro/caixa" | "/(app)/financeiro/comissoes" | "/(app)/financeiro/comissoes/calculo" | "/(app)/financeiro/comissoes/regras" | "/(app)/financeiro/conciliacao" | "/(app)/financeiro/formas-pagamento" | "/(app)/financeiro/regras" | "/(app)/gestor" | "/(app)/gestor/importar-vendas" | "/(app)/master" | "/(app)/master/empresas" | "/(app)/master/empresas/[id]" | "/(app)/master/permissoes" | "/(app)/master/permissoes/[id]" | "/(app)/master/usuarios" | "/(app)/master/usuarios/[id]" | "/(app)/metas" | "/(app)/metas/vendedor" | "/negado" | "/(app)/operacao" | "/(app)/operacao/acompanhamento" | "/(app)/operacao/agenda" | "/(app)/operacao/campanhas" | "/(app)/operacao/comissionamento" | "/(app)/operacao/conciliacao" | "/(app)/operacao/controle-sac" | "/(app)/operacao/documentos-viagens" | "/(app)/operacao/minhas-preferencias" | "/(app)/operacao/recados" | "/(app)/operacao/tarefas" | "/(app)/operacao/viagens" | "/(app)/operacao/viagens/nova" | "/(app)/operacao/viagens/[id]" | "/(app)/operacao/vouchers" | "/(app)/operacao/vouchers/novo" | "/(app)/operacao/vouchers/[id]" | "/(app)/orcamentos" | "/(app)/orcamentos/importar" | "/(app)/orcamentos/novo" | "/(app)/orcamentos/roteiros" | "/(app)/orcamentos/roteiros/[id]" | "/(app)/orcamentos/[id]" | "/(app)/orcamentos/[id]/editar" | "/(app)/parametros" | "/(app)/parametros/avisos" | "/(app)/parametros/cambios" | "/(app)/parametros/comissoes" | "/(app)/parametros/comissoes/templates" | "/(app)/parametros/crm" | "/(app)/parametros/empresa" | "/(app)/parametros/equipe" | "/(app)/parametros/escalas" | "/(app)/parametros/integracoes" | "/(app)/parametros/metas" | "/(app)/parametros/notificacoes" | "/(app)/parametros/orcamentos" | "/(app)/parametros/tipo-pacotes" | "/(app)/parametros/tipo-produtos" | "/(app)/parametros/vouchers" | "/(app)/perfil" | "/(app)/perfil/escala" | "/(app)/perfil/mfa" | "/(app)/perfil/onboarding" | "/(app)/perfil/personalizar" | "/(app)/relatorios" | "/(app)/relatorios/clientes" | "/(app)/relatorios/destinos" | "/(app)/relatorios/produtos" | "/(app)/relatorios/ranking" | "/(app)/relatorios/vendas" | "/test-env" | "/(app)/vendas" | "/(app)/vendas/importar" | "/(app)/vendas/nova" | "/(app)/vendas/[id]" | "/(app)/vendas/[id]/editar";
		RouteParams(): {
			"/(app)/admin/empresas/[id]": { id: string };
			"/(app)/admin/permissoes/[id]": { id: string };
			"/(app)/admin/tipos-usuario/[id]": { id: string };
			"/(app)/admin/usuarios/[id]": { id: string };
			"/api/v1/admin/empresas/[id]": { id: string };
			"/api/v1/admin/permissoes/[id]": { id: string };
			"/api/v1/admin/tipos-usuario/[id]": { id: string };
			"/api/v1/admin/tipos-usuario/[id]/permissoes": { id: string };
			"/api/v1/admin/usuarios/[id]": { id: string };
			"/api/v1/cidades/[id]": { id: string };
			"/api/v1/circuitos/[id]": { id: string };
			"/api/v1/clientes/[id]": { id: string };
			"/api/v1/clientes/[id]/acompanhantes": { id: string };
			"/api/v1/clientes/[id]/acompanhantes/[acompanhanteId]": { id: string; acompanhanteId: string };
			"/api/v1/financeiro/comissoes/regras/[id]": { id: string };
			"/api/v1/fornecedores/[id]": { id: string };
			"/api/v1/orcamentos/[id]": { id: string };
			"/api/v1/orcamentos/[id]/resumo-venda": { id: string };
			"/api/v1/pagamentos/[id]": { id: string };
			"/api/v1/pagamentos/[id]/conciliar": { id: string };
			"/api/v1/produtos/[id]": { id: string };
			"/api/v1/roteiros/[id]": { id: string };
			"/api/v1/todo/item/[id]": { id: string };
			"/api/v1/vendas/[id]": { id: string };
			"/api/v1/viagens/cliente/[id]": { id: string };
			"/api/v1/viagens/[id]": { id: string };
			"/api/v1/vouchers/[id]": { id: string };
			"/(app)/cadastros/circuitos/[id]": { id: string };
			"/(app)/cadastros/circuitos/[id]/editar": { id: string };
			"/(app)/cadastros/destinos/[id]": { id: string };
			"/(app)/cadastros/destinos/[id]/editar": { id: string };
			"/(app)/cadastros/fornecedores/[id]": { id: string };
			"/(app)/cadastros/fornecedores/[id]/editar": { id: string };
			"/(app)/cadastros/produtos/[id]": { id: string };
			"/(app)/cadastros/produtos/[id]/editar": { id: string };
			"/(app)/clientes/[id]": { id: string };
			"/(app)/clientes/[id]/editar": { id: string };
			"/(app)/master/empresas/[id]": { id: string };
			"/(app)/master/permissoes/[id]": { id: string };
			"/(app)/master/usuarios/[id]": { id: string };
			"/(app)/operacao/viagens/[id]": { id: string };
			"/(app)/operacao/vouchers/[id]": { id: string };
			"/(app)/orcamentos/roteiros/[id]": { id: string };
			"/(app)/orcamentos/[id]": { id: string };
			"/(app)/orcamentos/[id]/editar": { id: string };
			"/(app)/vendas/[id]": { id: string };
			"/(app)/vendas/[id]/editar": { id: string }
		};
		LayoutParams(): {
			"/(app)": { id?: string };
			"/": { id?: string; acompanhanteId?: string };
			"/(app)/admin": { id?: string };
			"/(app)/admin/aniversariantes": Record<string, never>;
			"/(app)/admin/avisos": Record<string, never>;
			"/(app)/admin/crm": Record<string, never>;
			"/(app)/admin/email": Record<string, never>;
			"/(app)/admin/empresas": { id?: string };
			"/(app)/admin/empresas/[id]": { id: string };
			"/(app)/admin/financeiro": Record<string, never>;
			"/(app)/admin/modulos-sistema": Record<string, never>;
			"/(app)/admin/parametros-importacao": Record<string, never>;
			"/(app)/admin/permissoes": { id?: string };
			"/(app)/admin/permissoes/[id]": { id: string };
			"/(app)/admin/planos": Record<string, never>;
			"/(app)/admin/tipos-usuario": { id?: string };
			"/(app)/admin/tipos-usuario/[id]": { id: string };
			"/(app)/admin/usuarios": { id?: string };
			"/(app)/admin/usuarios/[id]": { id: string };
			"/(app)/aniversariantes": Record<string, never>;
			"/api": { id?: string; acompanhanteId?: string };
			"/api/auth": Record<string, never>;
			"/api/auth/set-session": Record<string, never>;
			"/api/v1 2": Record<string, never>;
			"/api/v1": { id?: string; acompanhanteId?: string };
			"/api/v1/admin": { id?: string };
			"/api/v1/admin/auth": Record<string, never>;
			"/api/v1/admin/auth/mfa-status": Record<string, never>;
			"/api/v1/admin/auth/reset-mfa": Record<string, never>;
			"/api/v1/admin/auth/set-password": Record<string, never>;
			"/api/v1/admin/avisos": Record<string, never>;
			"/api/v1/admin/avisos/send": Record<string, never>;
			"/api/v1/admin/crm": Record<string, never>;
			"/api/v1/admin/email": Record<string, never>;
			"/api/v1/admin/email/test": Record<string, never>;
			"/api/v1/admin/empresas": { id?: string };
			"/api/v1/admin/empresas/[id]": { id: string };
			"/api/v1/admin/logs": Record<string, never>;
			"/api/v1/admin/maintenance": Record<string, never>;
			"/api/v1/admin/master-empresas": Record<string, never>;
			"/api/v1/admin/modulos-sistema": Record<string, never>;
			"/api/v1/admin/permissoes": { id?: string };
			"/api/v1/admin/permissoes/[id]": { id: string };
			"/api/v1/admin/planos": Record<string, never>;
			"/api/v1/admin/summary": Record<string, never>;
			"/api/v1/admin/system-modules": Record<string, never>;
			"/api/v1/admin/tipos-usuario": { id?: string };
			"/api/v1/admin/tipos-usuario/[id]": { id: string };
			"/api/v1/admin/tipos-usuario/[id]/permissoes": { id: string };
			"/api/v1/admin/usuarios": { id?: string };
			"/api/v1/admin/usuarios/[id]": { id: string };
			"/api/v1/agenda": Record<string, never>;
			"/api/v1/agenda/create": Record<string, never>;
			"/api/v1/agenda/delete": Record<string, never>;
			"/api/v1/agenda/range": Record<string, never>;
			"/api/v1/agenda/update": Record<string, never>;
			"/api/v1/cards": Record<string, never>;
			"/api/v1/cards/aniversario.svg": Record<string, never>;
			"/api/v1/cards/render.png": Record<string, never>;
			"/api/v1/cards/render.svg": Record<string, never>;
			"/api/v1/cards/render": Record<string, never>;
			"/api/v1/cidades": { id?: string };
			"/api/v1/cidades/[id]": { id: string };
			"/api/v1/circuitos": { id?: string };
			"/api/v1/circuitos/[id]": { id: string };
			"/api/v1/client-error": Record<string, never>;
			"/api/v1/clientes": { id?: string; acompanhanteId?: string };
			"/api/v1/clientes/avisos": Record<string, never>;
			"/api/v1/clientes/avisos/history": Record<string, never>;
			"/api/v1/clientes/avisos/send": Record<string, never>;
			"/api/v1/clientes/avisos/templates": Record<string, never>;
			"/api/v1/clientes/create": Record<string, never>;
			"/api/v1/clientes/delete": Record<string, never>;
			"/api/v1/clientes/historico": Record<string, never>;
			"/api/v1/clientes/list": Record<string, never>;
			"/api/v1/clientes/resolve-import": Record<string, never>;
			"/api/v1/clientes/template-dispatches": Record<string, never>;
			"/api/v1/clientes/templates": Record<string, never>;
			"/api/v1/clientes/templates/send": Record<string, never>;
			"/api/v1/clientes/[id]": { id: string; acompanhanteId?: string };
			"/api/v1/clientes/[id]/acompanhantes": { id: string; acompanhanteId?: string };
			"/api/v1/clientes/[id]/acompanhantes/[acompanhanteId]": { id: string; acompanhanteId: string };
			"/api/v1/conciliacao": Record<string, never>;
			"/api/v1/conciliacao/assign": Record<string, never>;
			"/api/v1/conciliacao/changes": Record<string, never>;
			"/api/v1/conciliacao/delete": Record<string, never>;
			"/api/v1/conciliacao/executions": Record<string, never>;
			"/api/v1/conciliacao/existing": Record<string, never>;
			"/api/v1/conciliacao/import": Record<string, never>;
			"/api/v1/conciliacao/list": Record<string, never>;
			"/api/v1/conciliacao/lookup": Record<string, never>;
			"/api/v1/conciliacao/options": Record<string, never>;
			"/api/v1/conciliacao/rateio-info": Record<string, never>;
			"/api/v1/conciliacao/revert": Record<string, never>;
			"/api/v1/conciliacao/run": Record<string, never>;
			"/api/v1/conciliacao/summary": Record<string, never>;
			"/api/v1/conciliacao/update-valores": Record<string, never>;
			"/api/v1/consultorias": Record<string, never>;
			"/api/v1/consultorias/ics": Record<string, never>;
			"/api/v1/convites": Record<string, never>;
			"/api/v1/convites/accept": Record<string, never>;
			"/api/v1/convites/send": Record<string, never>;
			"/api/v1/crm": Record<string, never>;
			"/api/v1/crm/library": Record<string, never>;
			"/api/v1/crm/signature": Record<string, never>;
			"/api/v1/cron": Record<string, never>;
			"/api/v1/cron/alerta-comissao": Record<string, never>;
			"/api/v1/cron/lembretes-consultoria": Record<string, never>;
			"/api/v1/dashboard": Record<string, never>;
			"/api/v1/dashboard/aniversariantes": Record<string, never>;
			"/api/v1/dashboard/consultorias": Record<string, never>;
			"/api/v1/dashboard/debug-aggregates": Record<string, never>;
			"/api/v1/dashboard/follow-ups": Record<string, never>;
			"/api/v1/dashboard/summary": Record<string, never>;
			"/api/v1/dashboard/viagens": Record<string, never>;
			"/api/v1/dashboard/widgets": Record<string, never>;
			"/api/v1/debug-comissao": Record<string, never>;
			"/api/v1/debug": Record<string, never>;
			"/api/v1/debug/escala-diag": Record<string, never>;
			"/api/v1/debug/permissions": Record<string, never>;
			"/api/v1/debug/vendas-recibos-diff": Record<string, never>;
			"/api/v1/debug/viagens-diag": Record<string, never>;
			"/api/v1/documentacao": Record<string, never>;
			"/api/v1/documentos-viagens": Record<string, never>;
			"/api/v1/documentos-viagens/create": Record<string, never>;
			"/api/v1/documentos-viagens/delete": Record<string, never>;
			"/api/v1/documentos-viagens/list": Record<string, never>;
			"/api/v1/documentos-viagens/save-template": Record<string, never>;
			"/api/v1/documentos-viagens/update": Record<string, never>;
			"/api/v1/equipe": Record<string, never>;
			"/api/v1/equipe/relacao": Record<string, never>;
			"/api/v1/financeiro": { id?: string };
			"/api/v1/financeiro/ajustes-vendas": Record<string, never>;
			"/api/v1/financeiro/ajustes-vendas/list": Record<string, never>;
			"/api/v1/financeiro/ajustes-vendas/save": Record<string, never>;
			"/api/v1/financeiro/caixa": Record<string, never>;
			"/api/v1/financeiro/comissoes": { id?: string };
			"/api/v1/financeiro/comissoes/calcular": Record<string, never>;
			"/api/v1/financeiro/comissoes/pagamento": Record<string, never>;
			"/api/v1/financeiro/comissoes/regras": { id?: string };
			"/api/v1/financeiro/comissoes/regras/[id]": { id: string };
			"/api/v1/financeiro/comissoes/vendedores": Record<string, never>;
			"/api/v1/financeiro/formas-pagamento": Record<string, never>;
			"/api/v1/fornecedores": { id?: string };
			"/api/v1/fornecedores/create": Record<string, never>;
			"/api/v1/fornecedores/[id]": { id: string };
			"/api/v1/health": Record<string, never>;
			"/api/v1/importar-vendas": Record<string, never>;
			"/api/v1/menu": Record<string, never>;
			"/api/v1/menu/prefs": Record<string, never>;
			"/api/v1/mural": Record<string, never>;
			"/api/v1/mural/bootstrap": Record<string, never>;
			"/api/v1/mural/company": Record<string, never>;
			"/api/v1/mural/read": Record<string, never>;
			"/api/v1/mural/recados": Record<string, never>;
			"/api/v1/operacao": Record<string, never>;
			"/api/v1/operacao/campanhas": Record<string, never>;
			"/api/v1/operacao/documentos-viagens": Record<string, never>;
			"/api/v1/operacao/preferencias": Record<string, never>;
			"/api/v1/operacao/recados": Record<string, never>;
			"/api/v1/operacao/sac": Record<string, never>;
			"/api/v1/orcamentos": { id?: string };
			"/api/v1/orcamentos/cidades-busca": Record<string, never>;
			"/api/v1/orcamentos/cliente-create": Record<string, never>;
			"/api/v1/orcamentos/clientes": Record<string, never>;
			"/api/v1/orcamentos/create": Record<string, never>;
			"/api/v1/orcamentos/delete": Record<string, never>;
			"/api/v1/orcamentos/importar": Record<string, never>;
			"/api/v1/orcamentos/interacao": Record<string, never>;
			"/api/v1/orcamentos/interaction": Record<string, never>;
			"/api/v1/orcamentos/list": Record<string, never>;
			"/api/v1/orcamentos/produtos": Record<string, never>;
			"/api/v1/orcamentos/save": Record<string, never>;
			"/api/v1/orcamentos/status": Record<string, never>;
			"/api/v1/orcamentos/tipos": Record<string, never>;
			"/api/v1/orcamentos/[id]": { id: string };
			"/api/v1/orcamentos/[id]/resumo-venda": { id: string };
			"/api/v1/pagamentos": { id?: string };
			"/api/v1/pagamentos/upload": Record<string, never>;
			"/api/v1/pagamentos/[id]": { id: string };
			"/api/v1/pagamentos/[id]/conciliar": { id: string };
			"/api/v1/paises": Record<string, never>;
			"/api/v1/parametros": Record<string, never>;
			"/api/v1/parametros/cambios": Record<string, never>;
			"/api/v1/parametros/commission-rules": Record<string, never>;
			"/api/v1/parametros/empresa": Record<string, never>;
			"/api/v1/parametros/equipe": Record<string, never>;
			"/api/v1/parametros/escalas": Record<string, never>;
			"/api/v1/parametros/metas": Record<string, never>;
			"/api/v1/parametros/nao-comissionaveis": Record<string, never>;
			"/api/v1/parametros/orcamentos-pdf": Record<string, never>;
			"/api/v1/parametros/sistema": Record<string, never>;
			"/api/v1/parametros/tipo-pacotes": Record<string, never>;
			"/api/v1/preferencias": Record<string, never>;
			"/api/v1/preferencias/base": Record<string, never>;
			"/api/v1/preferencias/cidades-busca": Record<string, never>;
			"/api/v1/preferencias/delete": Record<string, never>;
			"/api/v1/preferencias/list": Record<string, never>;
			"/api/v1/preferencias/save": Record<string, never>;
			"/api/v1/preferencias/share-accept": Record<string, never>;
			"/api/v1/preferencias/share-revoke": Record<string, never>;
			"/api/v1/preferencias/share": Record<string, never>;
			"/api/v1/produtos": { id?: string };
			"/api/v1/produtos/base": Record<string, never>;
			"/api/v1/produtos/create": Record<string, never>;
			"/api/v1/produtos/tarifas": Record<string, never>;
			"/api/v1/produtos/[id]": { id: string };
			"/api/v1/profile": Record<string, never>;
			"/api/v1/profile/signature": Record<string, never>;
			"/api/v1/push": Record<string, never>;
			"/api/v1/push/subscribe": Record<string, never>;
			"/api/v1/push/unsubscribe": Record<string, never>;
			"/api/v1/relatorios": Record<string, never>;
			"/api/v1/relatorios/base": Record<string, never>;
			"/api/v1/relatorios/cidades-busca": Record<string, never>;
			"/api/v1/relatorios/clientes": Record<string, never>;
			"/api/v1/relatorios/destinos": Record<string, never>;
			"/api/v1/relatorios/produtos-recibos": Record<string, never>;
			"/api/v1/relatorios/produtos": Record<string, never>;
			"/api/v1/relatorios/ranking-vendas": Record<string, never>;
			"/api/v1/relatorios/ranking": Record<string, never>;
			"/api/v1/relatorios/vendas-por-cliente": Record<string, never>;
			"/api/v1/relatorios/vendas-por-destino": Record<string, never>;
			"/api/v1/relatorios/vendas-por-produto": Record<string, never>;
			"/api/v1/relatorios/vendas": Record<string, never>;
			"/api/v1/roteiros": { id?: string };
			"/api/v1/roteiros/delete": Record<string, never>;
			"/api/v1/roteiros/dias-busca": Record<string, never>;
			"/api/v1/roteiros/gerar-orcamento": Record<string, never>;
			"/api/v1/roteiros/list": Record<string, never>;
			"/api/v1/roteiros/save": Record<string, never>;
			"/api/v1/roteiros/sugestoes-busca": Record<string, never>;
			"/api/v1/roteiros/sugestoes-remover": Record<string, never>;
			"/api/v1/roteiros/sugestoes-salvar": Record<string, never>;
			"/api/v1/roteiros/[id]": { id: string };
			"/api/v1/subdivisoes": Record<string, never>;
			"/api/v1/tarefas": Record<string, never>;
			"/api/v1/tarefas/clientes": Record<string, never>;
			"/api/v1/tarefas/usuarios": Record<string, never>;
			"/api/v1/tipo-produtos": Record<string, never>;
			"/api/v1/todo": { id?: string };
			"/api/v1/todo/batch": Record<string, never>;
			"/api/v1/todo/board": Record<string, never>;
			"/api/v1/todo/category": Record<string, never>;
			"/api/v1/todo/item": { id?: string };
			"/api/v1/todo/item/[id]": { id: string };
			"/api/v1/users": Record<string, never>;
			"/api/v1/users/aniversariantes": Record<string, never>;
			"/api/v1/user": Record<string, never>;
			"/api/v1/user/context": Record<string, never>;
			"/api/v1/user/profile": Record<string, never>;
			"/api/v1/vendas": { id?: string };
			"/api/v1/vendas/cadastro-base": Record<string, never>;
			"/api/v1/vendas/cadastro-save": Record<string, never>;
			"/api/v1/vendas/cancel": Record<string, never>;
			"/api/v1/vendas/cidades-busca": Record<string, never>;
			"/api/v1/vendas/complementares": Record<string, never>;
			"/api/v1/vendas/create": Record<string, never>;
			"/api/v1/vendas/gestor-equipe": Record<string, never>;
			"/api/v1/vendas/importar-contrato": Record<string, never>;
			"/api/v1/vendas/kpis": Record<string, never>;
			"/api/v1/vendas/list": Record<string, never>;
			"/api/v1/vendas/merge-candidates": Record<string, never>;
			"/api/v1/vendas/merge": Record<string, never>;
			"/api/v1/vendas/recibo-complementar-link": Record<string, never>;
			"/api/v1/vendas/recibo-complementar-remove": Record<string, never>;
			"/api/v1/vendas/recibo-delete": Record<string, never>;
			"/api/v1/vendas/recibo-edit": Record<string, never>;
			"/api/v1/vendas/recibo-notas": Record<string, never>;
			"/api/v1/vendas/recibo-principal": Record<string, never>;
			"/api/v1/vendas/status": Record<string, never>;
			"/api/v1/vendas/[id]": { id: string };
			"/api/v1/viagens": { id?: string };
			"/api/v1/viagens/cidades-busca": Record<string, never>;
			"/api/v1/viagens/clientes": Record<string, never>;
			"/api/v1/viagens/cliente": { id?: string };
			"/api/v1/viagens/cliente/[id]": { id: string };
			"/api/v1/viagens/create": Record<string, never>;
			"/api/v1/viagens/delete": Record<string, never>;
			"/api/v1/viagens/dossie-batch": Record<string, never>;
			"/api/v1/viagens/dossie": Record<string, never>;
			"/api/v1/viagens/list": Record<string, never>;
			"/api/v1/viagens/[id]": { id: string };
			"/api/v1/voucher-assets": Record<string, never>;
			"/api/v1/vouchers": { id?: string };
			"/api/v1/vouchers/create": Record<string, never>;
			"/api/v1/vouchers/delete": Record<string, never>;
			"/api/v1/vouchers/[id]": { id: string };
			"/api/v1/welcome-email": Record<string, never>;
			"/auth": Record<string, never>;
			"/auth/convite": Record<string, never>;
			"/auth/login": Record<string, never>;
			"/auth/logout": Record<string, never>;
			"/auth/mfa": Record<string, never>;
			"/auth/nova-senha": Record<string, never>;
			"/auth/recuperar-senha": Record<string, never>;
			"/auth/register": Record<string, never>;
			"/(app)/cadastros": { id?: string };
			"/(app)/cadastros/cidades": Record<string, never>;
			"/(app)/cadastros/circuitos": { id?: string };
			"/(app)/cadastros/circuitos/novo": Record<string, never>;
			"/(app)/cadastros/circuitos/[id]": { id: string };
			"/(app)/cadastros/circuitos/[id]/editar": { id: string };
			"/(app)/cadastros/destinos": { id?: string };
			"/(app)/cadastros/destinos/novo": Record<string, never>;
			"/(app)/cadastros/destinos/[id]": { id: string };
			"/(app)/cadastros/destinos/[id]/editar": { id: string };
			"/(app)/cadastros/estados": Record<string, never>;
			"/(app)/cadastros/fornecedores": { id?: string };
			"/(app)/cadastros/fornecedores/novo": Record<string, never>;
			"/(app)/cadastros/fornecedores/[id]": { id: string };
			"/(app)/cadastros/fornecedores/[id]/editar": { id: string };
			"/(app)/cadastros/lote": Record<string, never>;
			"/(app)/cadastros/paises": Record<string, never>;
			"/(app)/cadastros/produtos": { id?: string };
			"/(app)/cadastros/produtos/novo": Record<string, never>;
			"/(app)/cadastros/produtos/[id]": { id: string };
			"/(app)/cadastros/produtos/[id]/editar": { id: string };
			"/calculadora": Record<string, never>;
			"/(app)/clientes": { id?: string };
			"/(app)/clientes/novo": Record<string, never>;
			"/(app)/clientes/[id]": { id: string };
			"/(app)/clientes/[id]/editar": { id: string };
			"/(app)/comissoes": Record<string, never>;
			"/(app)/comissoes/fechamento": Record<string, never>;
			"/(app)/consultoria-online": Record<string, never>;
			"/(app)/dashboard": Record<string, never>;
			"/(app)/dashboard/admin": Record<string, never>;
			"/(app)/dashboard/financeiro": Record<string, never>;
			"/(app)/dashboard/geral": Record<string, never>;
			"/(app)/dashboard/gestor": Record<string, never>;
			"/(app)/dashboard/master": Record<string, never>;
			"/(app)/dashboard/vendedor": Record<string, never>;
			"/(app)/debug": Record<string, never>;
			"/(app)/diagnostico": Record<string, never>;
			"/(app)/documentacao": Record<string, never>;
			"/(app)/financeiro": Record<string, never>;
			"/(app)/financeiro/ajustes-vendas": Record<string, never>;
			"/(app)/financeiro/caixa": Record<string, never>;
			"/(app)/financeiro/comissoes": Record<string, never>;
			"/(app)/financeiro/comissoes/calculo": Record<string, never>;
			"/(app)/financeiro/comissoes/regras": Record<string, never>;
			"/(app)/financeiro/conciliacao": Record<string, never>;
			"/(app)/financeiro/formas-pagamento": Record<string, never>;
			"/(app)/financeiro/regras": Record<string, never>;
			"/(app)/gestor": Record<string, never>;
			"/(app)/gestor/importar-vendas": Record<string, never>;
			"/(app)/master": { id?: string };
			"/(app)/master/empresas": { id?: string };
			"/(app)/master/empresas/[id]": { id: string };
			"/(app)/master/permissoes": { id?: string };
			"/(app)/master/permissoes/[id]": { id: string };
			"/(app)/master/usuarios": { id?: string };
			"/(app)/master/usuarios/[id]": { id: string };
			"/(app)/metas": Record<string, never>;
			"/(app)/metas/vendedor": Record<string, never>;
			"/negado": Record<string, never>;
			"/(app)/operacao": { id?: string };
			"/(app)/operacao/acompanhamento": Record<string, never>;
			"/(app)/operacao/agenda": Record<string, never>;
			"/(app)/operacao/campanhas": Record<string, never>;
			"/(app)/operacao/comissionamento": Record<string, never>;
			"/(app)/operacao/conciliacao": Record<string, never>;
			"/(app)/operacao/controle-sac": Record<string, never>;
			"/(app)/operacao/documentos-viagens": Record<string, never>;
			"/(app)/operacao/minhas-preferencias": Record<string, never>;
			"/(app)/operacao/recados": Record<string, never>;
			"/(app)/operacao/tarefas": Record<string, never>;
			"/(app)/operacao/viagens": { id?: string };
			"/(app)/operacao/viagens/nova": Record<string, never>;
			"/(app)/operacao/viagens/[id]": { id: string };
			"/(app)/operacao/vouchers": { id?: string };
			"/(app)/operacao/vouchers/novo": Record<string, never>;
			"/(app)/operacao/vouchers/[id]": { id: string };
			"/(app)/orcamentos": { id?: string };
			"/(app)/orcamentos/importar": Record<string, never>;
			"/(app)/orcamentos/novo": Record<string, never>;
			"/(app)/orcamentos/roteiros": { id?: string };
			"/(app)/orcamentos/roteiros/[id]": { id: string };
			"/(app)/orcamentos/[id]": { id: string };
			"/(app)/orcamentos/[id]/editar": { id: string };
			"/(app)/parametros": Record<string, never>;
			"/(app)/parametros/avisos": Record<string, never>;
			"/(app)/parametros/cambios": Record<string, never>;
			"/(app)/parametros/comissoes": Record<string, never>;
			"/(app)/parametros/comissoes/templates": Record<string, never>;
			"/(app)/parametros/crm": Record<string, never>;
			"/(app)/parametros/empresa": Record<string, never>;
			"/(app)/parametros/equipe": Record<string, never>;
			"/(app)/parametros/escalas": Record<string, never>;
			"/(app)/parametros/integracoes": Record<string, never>;
			"/(app)/parametros/metas": Record<string, never>;
			"/(app)/parametros/notificacoes": Record<string, never>;
			"/(app)/parametros/orcamentos": Record<string, never>;
			"/(app)/parametros/tipo-pacotes": Record<string, never>;
			"/(app)/parametros/tipo-produtos": Record<string, never>;
			"/(app)/parametros/vouchers": Record<string, never>;
			"/(app)/perfil": Record<string, never>;
			"/(app)/perfil/escala": Record<string, never>;
			"/(app)/perfil/mfa": Record<string, never>;
			"/(app)/perfil/onboarding": Record<string, never>;
			"/(app)/perfil/personalizar": Record<string, never>;
			"/(app)/relatorios": Record<string, never>;
			"/(app)/relatorios/clientes": Record<string, never>;
			"/(app)/relatorios/destinos": Record<string, never>;
			"/(app)/relatorios/produtos": Record<string, never>;
			"/(app)/relatorios/ranking": Record<string, never>;
			"/(app)/relatorios/vendas": Record<string, never>;
			"/test-env": Record<string, never>;
			"/(app)/vendas": { id?: string };
			"/(app)/vendas/importar": Record<string, never>;
			"/(app)/vendas/nova": Record<string, never>;
			"/(app)/vendas/[id]": { id: string };
			"/(app)/vendas/[id]/editar": { id: string }
		};
		Pathname(): "/" | "/admin" | "/admin/aniversariantes" | "/admin/avisos" | "/admin/crm" | "/admin/email" | "/admin/empresas" | `/admin/empresas/${string}` & {} | "/admin/financeiro" | "/admin/modulos-sistema" | "/admin/parametros-importacao" | "/admin/permissoes" | `/admin/permissoes/${string}` & {} | "/admin/planos" | "/admin/tipos-usuario" | `/admin/tipos-usuario/${string}` & {} | "/admin/usuarios" | `/admin/usuarios/${string}` & {} | "/aniversariantes" | "/api/auth/set-session" | "/api/v1/admin/auth/mfa-status" | "/api/v1/admin/auth/reset-mfa" | "/api/v1/admin/auth/set-password" | "/api/v1/admin/avisos" | "/api/v1/admin/avisos/send" | "/api/v1/admin/crm" | "/api/v1/admin/email" | "/api/v1/admin/email/test" | "/api/v1/admin/empresas" | `/api/v1/admin/empresas/${string}` & {} | "/api/v1/admin/logs" | "/api/v1/admin/maintenance" | "/api/v1/admin/master-empresas" | "/api/v1/admin/modulos-sistema" | "/api/v1/admin/permissoes" | `/api/v1/admin/permissoes/${string}` & {} | "/api/v1/admin/planos" | "/api/v1/admin/summary" | "/api/v1/admin/system-modules" | "/api/v1/admin/tipos-usuario" | `/api/v1/admin/tipos-usuario/${string}` & {} | `/api/v1/admin/tipos-usuario/${string}/permissoes` & {} | "/api/v1/admin/usuarios" | `/api/v1/admin/usuarios/${string}` & {} | "/api/v1/agenda" | "/api/v1/agenda/create" | "/api/v1/agenda/delete" | "/api/v1/agenda/range" | "/api/v1/agenda/update" | "/api/v1/cards/aniversario.svg" | "/api/v1/cards/render.png" | "/api/v1/cards/render.svg" | "/api/v1/cards/render" | "/api/v1/cidades" | `/api/v1/cidades/${string}` & {} | "/api/v1/circuitos" | `/api/v1/circuitos/${string}` & {} | "/api/v1/client-error" | "/api/v1/clientes" | "/api/v1/clientes/avisos/history" | "/api/v1/clientes/avisos/send" | "/api/v1/clientes/avisos/templates" | "/api/v1/clientes/create" | "/api/v1/clientes/delete" | "/api/v1/clientes/historico" | "/api/v1/clientes/list" | "/api/v1/clientes/resolve-import" | "/api/v1/clientes/template-dispatches" | "/api/v1/clientes/templates/send" | `/api/v1/clientes/${string}` & {} | `/api/v1/clientes/${string}/acompanhantes` & {} | `/api/v1/clientes/${string}/acompanhantes/${string}` & {} | "/api/v1/conciliacao" | "/api/v1/conciliacao/assign" | "/api/v1/conciliacao/changes" | "/api/v1/conciliacao/delete" | "/api/v1/conciliacao/executions" | "/api/v1/conciliacao/existing" | "/api/v1/conciliacao/import" | "/api/v1/conciliacao/list" | "/api/v1/conciliacao/lookup" | "/api/v1/conciliacao/options" | "/api/v1/conciliacao/rateio-info" | "/api/v1/conciliacao/revert" | "/api/v1/conciliacao/run" | "/api/v1/conciliacao/summary" | "/api/v1/conciliacao/update-valores" | "/api/v1/consultorias" | "/api/v1/consultorias/ics" | "/api/v1/convites/accept" | "/api/v1/convites/send" | "/api/v1/crm/library" | "/api/v1/crm/signature" | "/api/v1/cron/alerta-comissao" | "/api/v1/cron/lembretes-consultoria" | "/api/v1/dashboard/aniversariantes" | "/api/v1/dashboard/consultorias" | "/api/v1/dashboard/debug-aggregates" | "/api/v1/dashboard/follow-ups" | "/api/v1/dashboard/summary" | "/api/v1/dashboard/viagens" | "/api/v1/dashboard/widgets" | "/api/v1/debug-comissao" | "/api/v1/debug/permissions" | "/api/v1/debug/vendas-recibos-diff" | "/api/v1/debug/viagens-diag" | "/api/v1/documentacao" | "/api/v1/documentos-viagens/create" | "/api/v1/documentos-viagens/delete" | "/api/v1/documentos-viagens/list" | "/api/v1/documentos-viagens/save-template" | "/api/v1/documentos-viagens/update" | "/api/v1/equipe/relacao" | "/api/v1/financeiro/ajustes-vendas" | "/api/v1/financeiro/ajustes-vendas/list" | "/api/v1/financeiro/ajustes-vendas/save" | "/api/v1/financeiro/caixa" | "/api/v1/financeiro/comissoes" | "/api/v1/financeiro/comissoes/calcular" | "/api/v1/financeiro/comissoes/pagamento" | "/api/v1/financeiro/comissoes/regras" | `/api/v1/financeiro/comissoes/regras/${string}` & {} | "/api/v1/financeiro/comissoes/vendedores" | "/api/v1/financeiro/formas-pagamento" | "/api/v1/fornecedores" | "/api/v1/fornecedores/create" | `/api/v1/fornecedores/${string}` & {} | "/api/v1/health" | "/api/v1/importar-vendas" | "/api/v1/menu/prefs" | "/api/v1/mural/bootstrap" | "/api/v1/mural/company" | "/api/v1/mural/read" | "/api/v1/mural/recados" | "/api/v1/operacao/campanhas" | "/api/v1/operacao/documentos-viagens" | "/api/v1/operacao/preferencias" | "/api/v1/operacao/recados" | "/api/v1/operacao/sac" | "/api/v1/orcamentos/cidades-busca" | "/api/v1/orcamentos/cliente-create" | "/api/v1/orcamentos/clientes" | "/api/v1/orcamentos/create" | "/api/v1/orcamentos/delete" | "/api/v1/orcamentos/importar" | "/api/v1/orcamentos/interacao" | "/api/v1/orcamentos/interaction" | "/api/v1/orcamentos/list" | "/api/v1/orcamentos/produtos" | "/api/v1/orcamentos/save" | "/api/v1/orcamentos/status" | "/api/v1/orcamentos/tipos" | `/api/v1/orcamentos/${string}` & {} | `/api/v1/orcamentos/${string}/resumo-venda` & {} | "/api/v1/pagamentos" | "/api/v1/pagamentos/upload" | `/api/v1/pagamentos/${string}` & {} | `/api/v1/pagamentos/${string}/conciliar` & {} | "/api/v1/paises" | "/api/v1/parametros/cambios" | "/api/v1/parametros/commission-rules" | "/api/v1/parametros/empresa" | "/api/v1/parametros/equipe" | "/api/v1/parametros/escalas" | "/api/v1/parametros/metas" | "/api/v1/parametros/nao-comissionaveis" | "/api/v1/parametros/orcamentos-pdf" | "/api/v1/parametros/sistema" | "/api/v1/parametros/tipo-pacotes" | "/api/v1/preferencias/base" | "/api/v1/preferencias/cidades-busca" | "/api/v1/preferencias/delete" | "/api/v1/preferencias/list" | "/api/v1/preferencias/save" | "/api/v1/preferencias/share-accept" | "/api/v1/preferencias/share-revoke" | "/api/v1/preferencias/share" | "/api/v1/produtos" | "/api/v1/produtos/base" | "/api/v1/produtos/create" | "/api/v1/produtos/tarifas" | `/api/v1/produtos/${string}` & {} | "/api/v1/profile/signature" | "/api/v1/push/subscribe" | "/api/v1/push/unsubscribe" | "/api/v1/relatorios/base" | "/api/v1/relatorios/cidades-busca" | "/api/v1/relatorios/clientes" | "/api/v1/relatorios/destinos" | "/api/v1/relatorios/produtos-recibos" | "/api/v1/relatorios/produtos" | "/api/v1/relatorios/ranking-vendas" | "/api/v1/relatorios/ranking" | "/api/v1/relatorios/vendas-por-cliente" | "/api/v1/relatorios/vendas-por-destino" | "/api/v1/relatorios/vendas-por-produto" | "/api/v1/relatorios/vendas" | "/api/v1/roteiros" | "/api/v1/roteiros/delete" | "/api/v1/roteiros/dias-busca" | "/api/v1/roteiros/gerar-orcamento" | "/api/v1/roteiros/list" | "/api/v1/roteiros/save" | "/api/v1/roteiros/sugestoes-busca" | "/api/v1/roteiros/sugestoes-remover" | "/api/v1/roteiros/sugestoes-salvar" | `/api/v1/roteiros/${string}` & {} | "/api/v1/subdivisoes" | "/api/v1/tarefas" | "/api/v1/tarefas/clientes" | "/api/v1/tarefas/usuarios" | "/api/v1/tipo-produtos" | "/api/v1/todo/batch" | "/api/v1/todo/board" | "/api/v1/todo/category" | "/api/v1/todo/item" | `/api/v1/todo/item/${string}` & {} | "/api/v1/users/aniversariantes" | "/api/v1/user/context" | "/api/v1/user/profile" | "/api/v1/vendas" | "/api/v1/vendas/cadastro-base" | "/api/v1/vendas/cadastro-save" | "/api/v1/vendas/cancel" | "/api/v1/vendas/cidades-busca" | "/api/v1/vendas/complementares" | "/api/v1/vendas/create" | "/api/v1/vendas/gestor-equipe" | "/api/v1/vendas/importar-contrato" | "/api/v1/vendas/kpis" | "/api/v1/vendas/list" | "/api/v1/vendas/merge-candidates" | "/api/v1/vendas/merge" | "/api/v1/vendas/recibo-complementar-link" | "/api/v1/vendas/recibo-complementar-remove" | "/api/v1/vendas/recibo-delete" | "/api/v1/vendas/recibo-edit" | "/api/v1/vendas/recibo-notas" | "/api/v1/vendas/recibo-principal" | "/api/v1/vendas/status" | `/api/v1/vendas/${string}` & {} | "/api/v1/viagens" | "/api/v1/viagens/cidades-busca" | "/api/v1/viagens/clientes" | `/api/v1/viagens/cliente/${string}` & {} | "/api/v1/viagens/create" | "/api/v1/viagens/delete" | "/api/v1/viagens/dossie-batch" | "/api/v1/viagens/dossie" | "/api/v1/viagens/list" | `/api/v1/viagens/${string}` & {} | "/api/v1/voucher-assets" | "/api/v1/vouchers" | "/api/v1/vouchers/create" | "/api/v1/vouchers/delete" | `/api/v1/vouchers/${string}` & {} | "/api/v1/welcome-email" | "/auth/convite" | "/auth/login" | "/auth/logout" | "/auth/mfa" | "/auth/nova-senha" | "/auth/recuperar-senha" | "/auth/register" | "/cadastros" | "/cadastros/cidades" | "/cadastros/circuitos" | "/cadastros/circuitos/novo" | `/cadastros/circuitos/${string}/editar` & {} | "/cadastros/destinos" | "/cadastros/destinos/novo" | `/cadastros/destinos/${string}/editar` & {} | "/cadastros/estados" | "/cadastros/fornecedores" | "/cadastros/fornecedores/novo" | `/cadastros/fornecedores/${string}/editar` & {} | "/cadastros/lote" | "/cadastros/paises" | "/cadastros/produtos" | "/cadastros/produtos/novo" | `/cadastros/produtos/${string}/editar` & {} | "/calculadora" | "/clientes" | "/clientes/novo" | `/clientes/${string}` & {} | `/clientes/${string}/editar` & {} | "/comissoes" | "/comissoes/fechamento" | "/consultoria-online" | "/dashboard/admin" | "/dashboard/financeiro" | "/dashboard/geral" | "/dashboard/gestor" | "/dashboard/master" | "/dashboard/vendedor" | "/debug" | "/diagnostico" | "/documentacao" | "/financeiro" | "/financeiro/ajustes-vendas" | "/financeiro/caixa" | "/financeiro/comissoes" | "/financeiro/comissoes/calculo" | "/financeiro/comissoes/regras" | "/financeiro/conciliacao" | "/financeiro/formas-pagamento" | "/financeiro/regras" | "/gestor/importar-vendas" | "/master" | "/master/empresas" | `/master/empresas/${string}` & {} | "/master/permissoes" | `/master/permissoes/${string}` & {} | "/master/usuarios" | `/master/usuarios/${string}` & {} | "/metas/vendedor" | "/negado" | "/operacao/acompanhamento" | "/operacao/agenda" | "/operacao/campanhas" | "/operacao/comissionamento" | "/operacao/conciliacao" | "/operacao/controle-sac" | "/operacao/documentos-viagens" | "/operacao/minhas-preferencias" | "/operacao/recados" | "/operacao/tarefas" | "/operacao/viagens" | "/operacao/viagens/nova" | `/operacao/viagens/${string}` & {} | "/operacao/vouchers" | "/operacao/vouchers/novo" | `/operacao/vouchers/${string}` & {} | "/orcamentos" | "/orcamentos/importar" | "/orcamentos/novo" | "/orcamentos/roteiros" | `/orcamentos/roteiros/${string}` & {} | `/orcamentos/${string}` & {} | `/orcamentos/${string}/editar` & {} | "/parametros" | "/parametros/avisos" | "/parametros/cambios" | "/parametros/crm" | "/parametros/empresa" | "/parametros/equipe" | "/parametros/escalas" | "/parametros/integracoes" | "/parametros/metas" | "/parametros/notificacoes" | "/parametros/orcamentos" | "/parametros/tipo-pacotes" | "/parametros/tipo-produtos" | "/parametros/vouchers" | "/perfil" | "/perfil/escala" | "/perfil/mfa" | "/perfil/onboarding" | "/perfil/personalizar" | "/relatorios" | "/relatorios/clientes" | "/relatorios/destinos" | "/relatorios/produtos" | "/relatorios/ranking" | "/relatorios/vendas" | "/test-env" | "/vendas" | "/vendas/importar" | "/vendas/nova" | `/vendas/${string}` & {} | `/vendas/${string}/editar` & {};
		ResolvedPathname(): `${"" | `/${string}`}${ReturnType<AppTypes['Pathname']>}`;
		Asset(): "/apple-touch-icon-v2.png" | "/apple-touch-icon-v3.png" | "/apple-touch-icon-v4.png" | "/apple-touch-icon.png" | "/assets/cards/themes-master/anniversary-purchase.svg" | "/assets/cards/themes-master/anniversary-trip.svg" | "/assets/cards/themes-master/birthday-elegant.png" | "/assets/cards/themes-master/birthday-elegant.svg" | "/assets/cards/themes-master/christmas-gold.png" | "/assets/cards/themes-master/christmas-gold.svg" | "/assets/cards/themes-master/client-day-premium.svg" | "/assets/cards/themes-master/countdown-travel.svg" | "/assets/cards/themes-master/document-reminder-clean.svg" | "/assets/cards/themes-master/easter-pastel.png" | "/assets/cards/themes-master/easter-pastel.svg" | "/assets/cards/themes-master/exclusive-offer.svg" | "/assets/cards/themes-master/fathers-day-classic.svg" | "/assets/cards/themes-master/inactive-soft-recovery.svg" | "/assets/cards/themes-master/long-holiday.svg" | "/assets/cards/themes-master/mothers-day-floral.png" | "/assets/cards/themes-master/mothers-day-floral.svg" | "/assets/cards/themes-master/new-year-celebration.png" | "/assets/cards/themes-master/new-year-celebration.svg" | "/assets/cards/themes-master/post-trip-light.svg" | "/assets/cards/themes-master/pre-embark-clean.svg" | "/assets/cards/themes-master/premium-elegant.svg" | "/assets/cards/themes-master/referral-soft.svg" | "/assets/cards/themes-master/repurchase-soft.svg" | "/assets/cards/themes-master/seasonal-campaign.svg" | "/assets/cards/themes-master/special-date-soft.svg" | "/assets/cards/themes-master/surprise-soft.svg" | "/assets/cards/themes-master/travel-opportunity.svg" | "/assets/cards/themes-master/travel-return-soft.svg" | "/assets/cards/themes-master/valentines-romantic.svg" | "/assets/cards/themes-master/vip-gold.svg" | "/assets/cards/themes-master/vip-upgrade.svg" | "/assets/cards/themes-master/welcome-clean.svg" | "/assets/cards/themes-master/womens-day-soft.png" | "/assets/cards/themes-master/womens-day-soft.svg" | "/brand/vtur-symbol.png" | "/brand/vtur-symbol.svg" | "/data/airports-iata-city.json" | "/favicon.ico" | "/favicon.png" | "/favicon.svg" | "/icon-192-v2.png" | "/icon-192-v3.png" | "/icon-192-v4.png" | "/icon-192.png" | "/icon-512-v2.png" | "/icon-512-v3.png" | "/icon-512-v4.png" | "/icon-512.png" | "/icon-source-v3.png" | "/icon-source-v4.png" | "/icons/icon-192x192.png" | "/icons/icon-512x512.png" | "/icons/maskable-192x192.png" | "/icons/maskable-512x512.png" | "/manifest-calculadora.webmanifest" | "/manifest.webmanifest" | "/sw-calculadora.js" | string & {};
	}
}