-- Migration: upsert airline IATA codes from official list
-- Generated from Cias_Aereas.xls (2026-04-09)
INSERT INTO airline_iata_codes (iata_code, airline_name)
VALUES
  ('GB', 'ABX Air'),
  ('A3', 'Aegean Airlines'),
  ('EI', 'Aer Lingus'),
  ('M0', 'Aero Mongolia'),
  ('P5', 'Aero Republica'),
  ('SU', 'Aeroflot'),
  ('XZ', 'Aeroitalia'),
  ('AR', 'Aerolineas Argentinas'),
  ('AM', 'Aeromexico'),
  ('AW', 'Africa World Airlines'),
  ('AH', 'Air Algérie'),
  ('G9', 'Air Arabia'),
  ('KC', 'Air Astana'),
  ('2A', 'Air Astra'),
  ('CC', 'Air Atlanta Icelandic'),
  ('UU', 'Air Austral'),
  ('BT', 'Air Baltic'),
  ('BP', 'Air Botswana'),
  ('SM', 'Air Cairo'),
  ('TY', 'Air Caledonie'),
  ('K6', 'Air Cambodia'),
  ('AC', 'Air Canada'),
  ('TX', 'Air Caraibes'),
  ('9H', 'Air Changan'),
  ('CA', 'Air China'),
  ('XK', 'Air Corsica'),
  ('EN', 'Air Dolomiti'),
  ('UX', 'Air Europa'),
  ('AF', 'Air France'),
  ('GT', 'Air Guilin'),
  ('LD', 'Air Hong Kong'),
  ('AI', 'Air India'),
  ('IX', 'Air India Express'),
  ('JS', 'Air Koryo'),
  ('NX', 'Air Macau'),
  ('MK', 'Air Mauritius'),
  ('4O', 'Air Montenegro'),
  ('NZ', 'Air New Zealand'),
  ('PX', 'Air Niugini'),
  ('YW', 'Air Nostrum'),
  ('P4', 'Air Peace'),
  ('YP', 'Air Premia'),
  ('HC', 'Air Senegal'),
  ('JU', 'Air Serbia'),
  ('HM', 'Air Seychelles'),
  ('VT', 'Air Tahiti'),
  ('TN', 'Air Tahiti Nui'),
  ('TC', 'Air Tanzania'),
  ('TS', 'Air Transat'),
  ('NF', 'Air Vanuatu'),
  ('SB', 'Aircalin'),
  ('RE', 'Airhub Airlines'),
  ('D4', 'Airline GEO SKY'),
  ('4Z', 'Airlink'),
  ('KJ', 'AIRZETA'),
  ('VF', 'AJet'),
  ('QP', 'Akasa Air'),
  ('AS', 'Alaska Airlines'),
  ('AP', 'Albastar'),
  ('UJ', 'AlMasria Universal Airlines'),
  ('8R', 'Amelia'),
  ('AA', 'American Airlines'),
  ('NH', 'ANA'),
  ('GP', 'APG Airlines'),
  ('DM', 'Arajet'),
  ('IZ', 'Arkia Israeli Airlines'),
  ('OZ', 'Asiana Airlines'),
  ('KP', 'ASKY'),
  ('3V', 'ASL Airlines Belgium'),
  ('5O', 'ASL Airlines France'),
  ('5H', 'ASL Airlines Ireland'),
  ('RC', 'Atlantic Airways'),
  ('5Y', 'Atlas Air'),
  ('OS', 'Austrian'),
  ('AV', 'Avianca'),
  ('LR', 'Avianca Costa Rica'),
  ('2K', 'Avianca Ecuador'),
  ('X9', 'Avion Express'),
  ('4X', 'Avion Express Malta'),
  ('J2', 'Azerbaijan Airlines'),
  ('S4', 'Azores Airlines'),
  ('AD', 'Azul Brazilian Airlines'),
  ('J4', 'Badr Airlines'),
  ('UP', 'Bahamasair'),
  ('QH', 'Bamboo Airways'),
  ('PG', 'Bangkok Airways'),
  ('ID', 'Batik Air'),
  ('OD', 'Batik Air Malaysia'),
  ('B5', 'BBN Airlines'),
  ('B2', 'Belavia Belarusian Airlines'),
  ('BG', 'Biman Bangladesh Airlines'),
  ('NT', 'Binter Canarias'),
  ('BZ', 'Blue Bird Airways'),
  ('OB', 'BoA Boliviana de Aviacion'),
  ('BA', 'British Airways'),
  ('SN', 'Brussels Airlines'),
  ('FB', 'Bulgaria Air'),
  ('QC', 'Camair-Co'),
  ('JD', 'Capital Airlines'),
  ('W8', 'Cargojet Airways'),
  ('CV', 'Cargolux'),
  ('BW', 'Caribbean Airlines'),
  ('V3', 'Carpatair'),
  ('CX', 'Cathay Pacific'),
  ('5J', 'Cebu Pacific'),
  ('5Z', 'CemAir'),
  ('CS', 'Chair Airlines'),
  ('CE', 'Chalair'),
  ('X7', 'Challenge Airlines (BE)'),
  ('5C', 'Challenge Airlines (IL)'),
  ('CI', 'China Airlines'),
  ('CK', 'China Cargo Airlines'),
  ('MU', 'China Eastern'),
  ('G5', 'China Express Airlines'),
  ('CF', 'China Postal Airlines'),
  ('CZ', 'China Southern Airlines'),
  ('KN', 'China United Airlines'),
  ('QG', 'Citilink'),
  ('WX', 'CityJet'),
  ('VE', 'Clic Air'),
  ('DE', 'Condor'),
  ('CM', 'COPA Airlines'),
  ('XC', 'Corendon Airlines'),
  ('SS', 'Corsair International'),
  ('OU', 'Croatia Airlines'),
  ('CU', 'Cubana'),
  ('CY', 'Cyprus Airways'),
  ('DN', 'DAN AIR'),
  ('DL', 'Delta Air Lines'),
  ('D0', 'DHL Air'),
  ('4Y', 'Discover Airlines'),
  ('SF', 'Domestic Airlines'),
  ('WK', 'Edelweiss Air'),
  ('MS', 'Egyptair'),
  ('LY', 'EL AL'),
  ('3E', 'Electra Airways'),
  ('EK', 'Emirates'),
  ('E7', 'Estafeta Cargo'),
  ('ET', 'Ethiopian Airlines'),
  ('EY', 'Etihad Airways'),
  ('YU', 'EuroAtlantic Airways'),
  ('QY', 'European Air Transport'),
  ('EW', 'Eurowings'),
  ('BR', 'EVA Air'),
  ('MG', 'Eznis Airways'),
  ('FN', 'Fastjet Zimbabwe'),
  ('FX', 'FedEx Express'),
  ('FJ', 'Fiji Airways'),
  ('AY', 'Finnair'),
  ('W2', 'FlexFlight'),
  ('IF', 'Fly Baghdad'),
  ('WV', 'Fly Namibia'),
  ('F3', 'flyadeal'),
  ('FZ', 'flydubai'),
  ('J7', 'FlyGabon'),
  ('XY', 'Flynas'),
  ('5F', 'FLYONE'),
  ('FH', 'Freebird Airlines'),
  ('BF', 'French Bee'),
  ('FU', 'Fuzhou Airlines'),
  ('GA', 'Garuda Indonesia'),
  ('A9', 'Georgian Airways'),
  ('ZQ', 'German Airways'),
  ('GE', 'Global Airways and Lift'),
  ('G6', 'GlobalX'),
  ('G3', 'GOL Linhas Aereas'),
  ('HB', 'Greater Bay Airlines'),
  ('GF', 'Gulf Air'),
  ('GX', 'GX Airlines'),
  ('HU', 'Hainan Airlines'),
  ('HA', 'Hawaiian Airlines'),
  ('NS', 'Hebei Airlines'),
  ('H3', 'Hello Jets'),
  ('H9', 'Himalaya Airlines'),
  ('RH', 'Hong Kong Air Cargo'),
  ('HX', 'Hong Kong Airlines'),
  ('UO', 'Hong Kong Express Airways'),
  ('IB', 'IBERIA'),
  ('6O', 'Iberojet'),
  ('E9', 'Iberojet Airlines'),
  ('QI', 'Ibom Air'),
  ('FI', 'Icelandair'),
  ('EO', 'Ikar'),
  ('6E', 'IndiGo'),
  ('IR', 'Iran Air'),
  ('B9', 'Iran Airtour Airline'),
  ('EP', 'Iran Aseman Airlines'),
  ('6H', 'Israir'),
  ('AZ', 'ITA Airways'),
  ('JL', 'Japan Airlines'),
  ('NU', 'Japan Transocean Air'),
  ('J9', 'Jazeera Airways'),
  ('JG', 'JD Airlines'),
  ('7C', 'Jeju Air'),
  ('B6', 'JetBlue'),
  ('WJ', 'JetSMART Argentina'),
  ('JA', 'JetSMART Chile'),
  ('JZ', 'JetSMART Peru'),
  ('LJ', 'Jin Air'),
  ('R5', 'Jordan Aviation'),
  ('HO', 'Juneyao Airlines'),
  ('RQ', 'Kam Air'),
  ('KQ', 'Kenya Airways'),
  ('KL', 'KLM'),
  ('KM', 'KM Malta Airlines'),
  ('KE', 'Korean Air'),
  ('KY', 'Kunming Airlines'),
  ('KU', 'Kuwait Airways'),
  ('B0', 'La Compagnie'),
  ('TM', 'LAM'),
  ('QV', 'Lao Airlines'),
  ('JJ', 'LATAM Airlines Brasil'),
  ('4C', 'LATAM Airlines Colombia'),
  ('XL', 'LATAM Airlines Ecuador'),
  ('LA', 'LATAM Airlines Group'),
  ('PZ', 'LATAM Airlines Paraguay'),
  ('LP', 'LATAM Airlines Peru'),
  ('M3', 'LATAM Cargo Brasil'),
  ('UC', 'LATAM Cargo Chile'),
  ('FC', 'Link Airways'),
  ('JT', 'Lion Air'),
  ('LM', 'Loganair'),
  ('GJ', 'Loong Air'),
  ('LO', 'LOT Polish Airlines'),
  ('8L', 'Lucky Air'),
  ('LH', 'Lufthansa'),
  ('LH', 'Lufthansa Cargo'),
  ('CL', 'Lufthansa CityLine'),
  ('LG', 'Luxair'),
  ('MD', 'Madagascar Airlines'),
  ('MH', 'Malaysia Airlines'),
  ('AE', 'Mandarin Airlines'),
  ('MP', 'Martinair Cargo'),
  ('M7', 'MasAir'),
  ('L6', 'Mauritania Airlines International'),
  ('4M', 'Mavi Gök Airlines (MGA)'),
  ('ME', 'MEA'),
  ('OM', 'MIAT Mongolian Airlines'),
  ('MB', 'MNG Airlines'),
  ('8M', 'Myanmar Airways International'),
  ('UB', 'Myanmar National Airlines'),
  ('N8', 'National Airlines'),
  ('ON', 'Nauru Airlines'),
  ('NO', 'Neos'),
  ('NE', 'Nesma Airlines'),
  ('7H', 'New Pacific Airlines'),
  ('NP', 'Nile Air'),
  ('KZ', 'Nippon Cargo Airlines'),
  ('DD', 'Nok Air'),
  ('Y7', 'NordStar'),
  ('N4', 'Nordwind Airlines'),
  ('N7', 'Norra'),
  ('BJ', 'Nouvelair'),
  ('BK', 'Okay Airways'),
  ('OA', 'Olympic Air'),
  ('WY', 'Oman Air'),
  ('OF', 'Overland Airways'),
  ('PK', 'Pakistan International Airlines'),
  ('2P', 'PAL Express'),
  ('ZP', 'Paranair'),
  ('PC', 'Pegasus Airlines'),
  ('UF', 'Petroleum Air Services'),
  ('PR', 'Philippine Airlines'),
  ('PU', 'Plus Ultra'),
  ('PO', 'Polar Air Cargo'),
  ('HP', 'PopulAir'),
  ('M4', 'Poste Air Cargo'),
  ('PW', 'Precision Air'),
  ('P6', 'Privilege Style'),
  ('P0', 'Proflight Zambia'),
  ('QF', 'Qantas'),
  ('QR', 'Qatar Airways'),
  ('IQ', 'Qazaq Air'),
  ('QW', 'Qingdao Airlines'),
  ('4S', 'Red Sea Airlines'),
  ('FV', 'Rossiya Airlines'),
  ('AT', 'Royal Air Maroc'),
  ('BI', 'Royal Brunei'),
  ('RJ', 'Royal Jordanian'),
  ('DR', 'Ruili Airlines'),
  ('7R', 'RusLine'),
  ('WB', 'RwandAir'),
  ('S7', 'S7 Airlines'),
  ('FA', 'Safair'),
  ('OV', 'Salam Air'),
  ('SK', 'SAS'),
  ('SP', 'SATA Air Acores'),
  ('SV', 'Saudi Arabian Airlines'),
  ('DV', 'SCAT Airlines'),
  ('TR', 'Scoot'),
  ('O3', 'SF Airlines'),
  ('SC', 'Shandong Airlines'),
  ('FM', 'Shanghai Airlines'),
  ('ZH', 'Shenzhen Airlines'),
  ('3U', 'Sichuan Airlines'),
  ('7L', 'Silk Way West Airlines'),
  ('SQ', 'Singapore Airlines'),
  ('H2', 'SKY Airline'),
  ('GQ', 'Sky express'),
  ('PQ', 'SkyUp Airlines'),
  ('5N', 'Smartavia'),
  ('QS', 'Smartwings'),
  ('IE', 'Solomon Airlines'),
  ('SZ', 'Somon Air'),
  ('SA', 'South African Airways'),
  ('WN', 'Southwest Airlines'),
  ('2S', 'Southwind Airlines'),
  ('SG', 'SpiceJet'),
  ('UL', 'SriLankan Airlines'),
  ('JX', 'STARLUX Airlines'),
  ('SY', 'Sun Country Airlines'),
  ('XQ', 'SunExpress'),
  ('Y8', 'Suparna Airlines'),
  ('WT', 'Swiftair'),
  ('LX', 'SWISS'),
  ('RB', 'Syrianair'),
  ('TW', 'T''way Air'),
  ('DT', 'TAAG Angola Airlines'),
  ('TA', 'TACA'),
  ('5U', 'TAG Airlines'),
  ('TP', 'TAP Air Portugal'),
  ('RO', 'TAROM'),
  ('TG', 'Thai Airways International'),
  ('SL', 'Thai Lion Air'),
  ('GS', 'Tianjin Airlines'),
  ('TV', 'Tibet Airlines'),
  ('X3', 'TUIfly'),
  ('TU', 'Tunisair'),
  ('TK', 'Turkish Airlines'),
  ('U8', 'TUS Airways'),
  ('B7', 'UNI AIR'),
  ('UA', 'United Airlines'),
  ('UN', 'United Nigeria Airlines'),
  ('5X', 'UPS Airlines'),
  ('U6', 'Ural Airlines'),
  ('UQ', 'Urumqi Air'),
  ('BS', 'US-Bangla Airlines'),
  ('UT', 'UTair'),
  ('HY', 'Uzbekistan Airways'),
  ('VJ', 'Vietjet'),
  ('VN', 'Vietnam Airlines'),
  ('VS', 'Virgin Atlantic'),
  ('VA', 'Virgin Australia'),
  ('Y4', 'Volaris'),
  ('V7', 'Volotea'),
  ('VY', 'Vueling'),
  ('EB', 'Wamos Air'),
  ('PN', 'West Air'),
  ('WS', 'WestJet'),
  ('WI', 'White coloured by you'),
  ('WF', 'Wideroe'),
  ('2W', 'World2Fly'),
  ('MF', 'Xiamen Airlines'),
  ('YG', 'YTO Cargo Airlines')
ON CONFLICT (iata_code) DO NOTHING;